"""
Explanation behavior using an explicand representation's self-weighted importance, as
proposed by Crabbe et al. Label-Free Explainability for Unsupervised Models.
https://arxiv.org/abs/2203.01928
"""

import torch
import torch.nn as nn


class WeightedScore(nn.Module):
    """
    Module class for label-free feature importance proposed by Crabbe et al. 2022.

    Args:
    ----
        encoder: Encoder module to explain.
    """

    def __init__(self, encoder: nn.Module) -> None:
        super().__init__()
        self.encoder = encoder
        self.weight = None

    def forward(self, explicand: torch.Tensor) -> torch.Tensor:
        assert self.weight is not None, (
            "WeightedScore.weight needs to be generated by calling the method"
            " WeightedScore.generate_weight"
        )
        explicand_rep = self.encoder(explicand)
        return (self.weight * explicand_rep).sum(dim=-1)

    def generate_weight(self, x: torch.Tensor) -> None:
        """Use inputs to generate and update weight for computing weighted score."""
        self.weight = self.encoder(x).detach()
